build:
	mvn package

maven-info:
	#echo out some info about the maven installation
	mvn --version

run:
	# run the app
	java -cp target/my-app-1.0-SNAPSHOT.jar com.mycompany.app.App

java-info:
	javac -version

clean:
	mvn clean

all: clean build run